export const site = {
  name: "Finopia Services",
  founder: "Yogesh Kadam CFP®",
  tagline: "Financial literacy, mutual fund guidance and insurance support for families in Karad",
  seoDescription: "Finopia Services helps families in Karad build financial confidence with practical financial literacy, mutual fund guidance, insurance support and investor awareness programs.",
  seoDescriptionMr: "फिनोपिया सर्व्हिसेस कराडमध्ये आर्थिक साक्षरता, म्युच्युअल फंड मार्गदर्शन आणि विमा सहाय्याद्वारे कुटुंबांना आर्थिक आत्मविश्वास देण्यास मदत करते.",
  keywords: ["financial literacy", "mutual fund distributor", "insurance solutions", "Yogesh Kadam CFP", "Karad", "पैशाचे शहाणपण", "family financial planning"],
  phone: "+91 97393 79696",
  office: "+91 99776 96796",
  email: "finopiaservices@gmail.com",
  whatsapp: "+919977696796",
  address: "Office No. 1, Sai Samarth Complex, above Gaurav Surgicals, near Shree Hospital, Wakhan Road, Karad – 415110, Maharashtra",
  addressMr: "ऑफिस क्र. १, साई समर्थ कॉम्प्लेक्स, गौरव सर्जिकल्सच्या वर, श्री हॉस्पिटलजवळ, वाखाण रोड, कराड – ४१५११०, महाराष्ट्र",
  instagram: "https://www.instagram.com/finopia_services_",
  youtube: "https://youtube.com/@finopiaservices",
  facebook: "https://www.facebook.com/share/1YnxV29NV1/",
  compliance: {
    arn: "ARN-337302",
    euin: "E641374",
    validity: "05 June 2028",
    cfp: "126010",
    insurer: "HDFC Life Insurance Company Limited",
    agency: "HDF01946314",
  },
} as const;

export const navItems = [
  ["Home", "मुख्यपृष्ठ", "/"],
  ["About", "आमच्याविषयी", "/about"],
  ["Services", "सेवा", "/services"],
  ["Financial Literacy", "आर्थिक साक्षरता", "/financial-literacy"],
  ["Book", "पुस्तक", "/book"],
  ["Insights", "लेख", "/blogs"],
  ["Gallery", "छायाचित्रे", "/gallery"],
  ["Contact", "संपर्क", "/contact"],
] as const;

export const services = [
  { icon: "chart", title: "Mutual Fund Distribution", titleMr: "म्युच्युअल फंड वितरण", description: "Help selecting and accessing suitable mutual fund products with clear, process-led support.", descriptionMr: "स्पष्ट आणि प्रक्रियाधारित सहाय्याने योग्य म्युच्युअल फंड उत्पादने समजून घेण्यास व निवडण्यास मदत." },
  { icon: "shield", title: "Life Insurance Solutions", titleMr: "जीवन विमा उपाय", description: "Protection-focused solutions designed around responsibilities, dependants and life stages.", descriptionMr: "जबाबदाऱ्या, अवलंबित व्यक्ती आणि जीवनातील टप्पे लक्षात घेऊन संरक्षणकेंद्रित उपाय." },
  { icon: "heart", title: "Health Insurance Solutions", titleMr: "आरोग्य विमा उपाय", description: "Guidance to understand health cover, exclusions and the importance of preparedness.", descriptionMr: "आरोग्य विमा संरक्षण, अपवाद आणि आर्थिक तयारीचे महत्त्व समजून घेण्यासाठी मार्गदर्शन." },
  { icon: "book", title: "Financial Literacy Programs", titleMr: "आर्थिक साक्षरता कार्यक्रम", description: "Practical learning experiences that turn financial concepts into everyday habits.", descriptionMr: "आर्थिक संकल्पनांचे दैनंदिन सवयींमध्ये रूपांतर करणारे व्यावहारिक शिक्षण." },
  { icon: "users", title: "Investor Awareness Programs", titleMr: "गुंतवणूकदार जागरूकता कार्यक्रम", description: "Clear, compliant education that helps participants ask better financial questions.", descriptionMr: "सहभागींना योग्य आर्थिक प्रश्न विचारण्यास मदत करणारे स्पष्ट आणि नियमसुसंगत शिक्षण." },
  { icon: "family", title: "Family Financial Management", titleMr: "कौटुंबिक आर्थिक व्यवस्थापन", description: "Simple frameworks for household cash flow, protection, goals and shared decisions.", descriptionMr: "घरगुती रोख प्रवाह, संरक्षण, उद्दिष्टे आणि सामूहिक निर्णयांसाठी सोप्या चौकटी." },
] as const;

export const articles = [
  {
    slug: "family-money-conversation",
    category: "Money basics",
    categoryMr: "पैशाची मूलतत्त्वे",
    title: "The quiet power of a family money conversation",
    titleMr: "घरात पैशाबद्दल शांतपणे बोलण्याची ताकद",
    excerpt: "A useful money conversation is not a lecture. It is a shared check-in about responsibilities, goals and the decisions that deserve clarity.",
    excerptMr: "पैशावरची चांगली चर्चा म्हणजे उपदेश नव्हे. जबाबदाऱ्या, ध्येये आणि स्पष्टता लागणारे निर्णय यावर कुटुंबाने एकत्र बसून केलेला संवाद आहे.",
    read: "6 min read",
    readMr: "६ मिनिटांचे वाचन",
    tone: "mint",
    body: [
      "Most families make financial decisions in fragments: one conversation about school fees, another about a loan, another about insurance, and a hurried discussion when an investment form needs a signature. The result is that money becomes a source of pressure instead of shared understanding.",
      "A family money conversation works best when it is calm, regular and practical. Start with three questions: what must be paid soon, what must be protected, and what future goal needs attention now? These questions keep the discussion grounded in real life.",
      "The purpose is not to agree on everything immediately. The purpose is to make assumptions visible. Once everyone knows the priorities, even small decisions become easier to explain and review.",
    ],
    bodyMr: [
      "अनेक घरांमध्ये पैशाचे निर्णय तुकड्या-तुकड्याने घेतले जातात. कधी शाळेच्या फीबद्दल, कधी कर्जाबद्दल, कधी विम्याबद्दल, तर कधी एखाद्या गुंतवणुकीच्या फॉर्मवर सही करायची म्हणून घाईघाईत चर्चा होते. त्यामुळे पैसा हा समजुतीचा विषय न राहता ताणाचा विषय बनतो.",
      "घरातील पैशाची चर्चा शांत, नियमित आणि व्यवहार्य असेल तर ती अधिक उपयोगी ठरते. सुरुवात तीन प्रश्नांनी करा: लवकर कोणते खर्च येणार आहेत, कोणत्या जबाबदाऱ्यांना संरक्षणाची गरज आहे, आणि कोणत्या भविष्यातील ध्येयासाठी आजपासून तयारी हवी आहे?",
      "या चर्चेचा उद्देश लगेच सगळ्यांचे मत एकसारखे करणे नाही. उद्देश आहे गृहितके स्पष्ट करणे. प्राधान्यक्रम समजले की छोटे निर्णयही शांतपणे घेता आणि समजावता येतात.",
    ],
  },
  {
    slug: "small-financial-systems",
    category: "Financial discipline",
    categoryMr: "आर्थिक शिस्त",
    title: "Small systems beat big financial resolutions",
    titleMr: "मोठ्या संकल्पांपेक्षा छोट्या आर्थिक सवयी जास्त उपयोगी",
    excerpt: "Financial discipline rarely comes from a dramatic promise. It grows from simple systems that repeat even on ordinary busy days.",
    excerptMr: "आर्थिक शिस्त मोठ्या घोषणांनी येत नाही. रोजच्या गडबडीतही टिकून राहतील अशा सोप्या पद्धतींमधून ती तयार होते.",
    read: "4 min read",
    readMr: "४ मिनिटांचे वाचन",
    tone: "blue",
    body: [
      "A resolution sounds powerful on the day it is made, but money habits are tested on ordinary days. A salary gets credited, bills arrive, a family need appears, and the month moves quickly. Without a system, even good intentions become difficult to follow.",
      "Begin with one repeatable rule. Separate essential expenses, protection needs, savings and flexible spending as soon as income comes in. The amounts can be modest; the rhythm matters more than perfection.",
      "A small system also reduces guilt. Instead of asking whether you were financially perfect this month, ask whether the system was followed and what needs a small adjustment next month.",
    ],
    bodyMr: [
      "संकल्प केला त्या दिवशी तो प्रभावी वाटतो; पण आर्थिक सवयींची खरी परीक्षा साध्या दिवसांत होते. पगार जमा होतो, बिले येतात, घरातील गरजा समोर येतात आणि महिना पटकन पुढे जातो. पद्धत नसेल तर चांगला हेतू असूनही सातत्य राखणे कठीण होते.",
      "एक सोपा, पुन्हा-पुन्हा करता येणारा नियम ठरवा. उत्पन्न आले की आवश्यक खर्च, संरक्षण, बचत आणि लवचिक खर्च यांची विभागणी करा. रक्कम लहान असली तरी चालते; नियमितता अधिक महत्त्वाची आहे.",
      "छोटी पद्धत अपराधीपणाही कमी करते. या महिन्यात मी परिपूर्ण आर्थिक वागलो का, असे विचारण्याऐवजी पद्धत पाळली का आणि पुढच्या महिन्यासाठी कोणता छोटा बदल हवा, हे पाहा.",
    ],
  },
  {
    slug: "protection-first-insurance",
    category: "Insurance literacy",
    categoryMr: "विमा साक्षरता",
    title: "Protection first: understanding what insurance is for",
    titleMr: "संरक्षण प्रथम: विम्याचा खरा उपयोग समजून घ्या",
    excerpt: "Insurance becomes clearer when we see it first as protection for responsibilities, not as a shortcut for returns.",
    excerptMr: "विमा हा परताव्याचा शॉर्टकट नसून जबाबदाऱ्यांचे संरक्षण आहे, असे पाहिल्यावर त्याचा अर्थ अधिक स्पष्ट होतो.",
    read: "7 min read",
    readMr: "७ मिनिटांचे वाचन",
    tone: "sand",
    body: [
      "Insurance is often discussed through premium, tax benefit or maturity value. Those details matter, but they can hide the first question: what responsibility needs protection if income is interrupted or a health event creates a large cost?",
      "A protection-first view begins with people and obligations. Dependants, loans, education goals, medical preparedness and household stability should come before product comparisons.",
      "When the purpose is clear, the conversation becomes more responsible. You can review cover amount, exclusions, waiting periods, affordability and claim process with a better lens.",
    ],
    bodyMr: [
      "विम्याची चर्चा अनेकदा प्रीमियम, करसवलत किंवा मॅच्युरिटी रक्कम याभोवती फिरते. हे मुद्दे महत्त्वाचे आहेत; पण पहिला प्रश्न वेगळा आहे: उत्पन्न थांबले किंवा आरोग्याशी संबंधित मोठा खर्च आला तर कोणत्या जबाबदाऱ्यांना संरक्षण हवे?",
      "संरक्षण-केंद्रित विचार व्यक्ती आणि जबाबदाऱ्यांपासून सुरू होतो. अवलंबित व्यक्ती, कर्ज, शिक्षणाची ध्येये, वैद्यकीय तयारी आणि घराची स्थिरता यांचा विचार उत्पादनांच्या तुलनेपूर्वी व्हायला हवा.",
      "उद्देश स्पष्ट झाला की चर्चा अधिक जबाबदार होते. कव्हरची रक्कम, अपवाद, प्रतीक्षा कालावधी, परवड आणि क्लेम प्रक्रिया यांचा विचार अधिक योग्य नजरेने करता येतो.",
    ],
  },
] as const;
